<?php

/**
 * @file
 */
/**
 * Implements hook_permission().
 */
function mrbs_permission() {
  return array(
    'mrbs view' => array(
      'title' => t('MRBS View Permission'),
      'description' => t('Acces to MRBS with view permision.'),
    ),
    'mrbs bookings' => array(
      'title' => t('MRBS Booking permission'),
      'description' => t('Acces to MRBS with Booking permisions.'),
    ),
    'mrbs admin' => array(
      'title' => t('MRBS Admin permission'),
      'description' => t('Acces to MRBS with Admin permisions.'),
    ),
  );
}

